#ifndef HITTABLE_BASE_INC
#define HITTABLE_BASE_INC

#extension GL_GOOGLE_include_directive : enable

struct Primitive {
  mat4 modelMatrix;
  vec4 bounds;
  vec4 center0;  // center0 xyz, time0 w
  vec4 center1;  // center1 xyz, time1 w

  float radius;
  float k;

  uint primitiveType;
  uint materialIndex;
};

layout(std430, set = 0, binding = 4) buffer PrimitiveBuffer {
  Primitive primitives[];
};

#endif  // HITTABLE_BASE_INC
