name: Build Web

on:
  push:
    branches: [master]

jobs:
  build:
    name: Web Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: install vulkan sdk
        run: |
          wget -O vulkansdk-linux-x86_64-1.2.154.0.tar.gz https://vulkan.lunarg.com/sdk/download/1.2.154.0/linux/vulkansdk-linux-x86_64-1.2.154.0.tar.gz?Human=true
          tar -xvf ./vulkansdk-linux-x86_64-1.2.154.0.tar.gz
          echo "$HOME/1.2.154.0/x86_64/bin" >> $GITHUB_PATH
          glslc --version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm ci

      - name: Build Prod
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
